name: '$(Build.SourceBranchName) $(Date:yyyy)-$(Date:MM)-$(Date:dd) ($(Rev:rr))'

schedules:
    - cron: '0 22 * * *' # UTC Timezone
      displayName: 'Daily midnight (CET) validation deployment to run local tests'
      branches:
          include:
              - main
      always: true # since something may have been directly changed in the orgs

trigger:
    branches:
        include:
            - main
            - rc/*
            - patch/*
    paths:
        include:
            - force-app/*

pool:
    vmImage: 'ubuntu-latest'

parameters:
    - name: VALIDATION
      type: boolean
      default: true
    - name: RUN_TEST_PARAMETER
      type: string
      default: RunLocalTests

variables:
    TARGET_BRANCH_REF: $(System.PullRequest.TargetBranch)
    DELETE: refs/heads/

stages:
    - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
          - template: .azure/templates/scheduled-tests.yml

    - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          - template: .azure/templates/validate.yml

    - stage: QA_deployment
      displayName: 'Deployment to QA and lower environments'
      condition: and(
          eq(variables['Build.Reason'], 'IndividualCI'),
          startsWith( variables['Build.SourceBranch'], 'refs/heads/main' )
          )
      jobs:
          - job: 'Deploy'
            strategy:
                matrix:
                    CICD:
                        ENVIRONMENT: 'CICD'
                    # QA:
                    #   ENVIRONMENT: 'QA'
                    # TODO: add lower environments
            container: salesforce/salesforcedx:latest-full
            steps:
                - template: .azure/templates/deploy.yml
                  parameters:
                      VALIDATION: false
                      RUN_TEST_PARAMETER: 'NoTestRun'
                      DESTINATION_ENVIRONMENT: $ENVIRONMENT

    - stage: UAT_deployment
      displayName: 'Deployment to UAT'
      condition: and(
          eq(variables['Build.Reason'], 'IndividualCI'),
          startsWith( variables['Build.SourceBranch'], 'refs/heads/rc' )
          )
      jobs:
          - deployment: 'Deploy_UAT'
            displayName: 'Deploy UAT'
            container: salesforce/salesforcedx:latest-full
            environment: UAT
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - checkout: self
                            - template: .azure/templates/deploy.yml
                              parameters:
                                  VALIDATION: ${{ parameters.VALIDATION }}
                                  RUN_TEST_PARAMETER: ${{ parameters.RUN_TEST_PARAMETER }}
                                  DESTINATION_ENVIRONMENT: UAT

    - stage: PRODUCTION_deployment
      displayName: 'Deployment to PRODUCTION'
      condition: and(
          eq(variables['Build.Reason'], 'Manual'),
          or(
          startsWith( variables['Build.SourceBranch'], 'refs/heads/rc' ),
          startsWith( variables['Build.SourceBranch'], 'refs/heads/patch' )
          ))
      jobs:
          - deployment: 'Deploy_PRODUCTION'
            displayName: 'Deploy PRODUCTION'
            container: salesforce/salesforcedx:latest-full
            environment: PRODUCTION
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - checkout: self
                            - template: .azure/templates/deploy.yml
                              parameters:
                                  VALIDATION: ${{ parameters.VALIDATION }}
                                  RUN_TEST_PARAMETER: ${{ parameters.RUN_TEST_PARAMETER }}
                                  DESTINATION_ENVIRONMENT: PRODUCTION
