stages:
    # Note: the following 2 deployment jobs are separated because the value of the TARGET_ORG matrix variable is not set dynamically.
    - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/main') }}:
          - stage: qa_deployment
            displayName: 'Deployment to QA and lower environments'
            jobs:
                - job: Deploy
                  strategy:
                      matrix:
                          INT:
                              TARGET_ORG: 'INT'
                          # QA:
                          #   TARGET_ORG: 'QA'
                          # TODO: add lower environments
                  container:
                      image: nakamapartneringservices/nakama-pipelines
                      endpoint: DockerHubNakama
                  steps:
                      - template: deploy.yml
                        parameters:
                            # Note: need parenthesis around in order for the matrix variable to be expanded properly as a parameter in the displayName.
                            TARGET_ORG: $(TARGET_ORG)
                            USE_MOST_RECENT: false
                            DRY_RUN: false
                            TEST_LEVEL: 'NoTestRun'
                            TESTS: ''

    - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/rc') }}:
          - stage: uat_deployment
            displayName: 'Deployment to UAT'
            jobs:
                - deployment: Deploy_UAT
                  displayName: 'Deploy UAT'
                  container:
                      image: nakamapartneringservices/nakama-pipelines
                      endpoint: DockerHubNakama
                  environment: UAT
                  strategy:
                      runOnce:
                          deploy:
                              steps:
                                  - template: deploy.yml
                                    parameters:
                                        # Note: need parenthesis around in order for the matrix variable to be expanded properly as a parameter in the displayName.
                                        TARGET_ORG: UAT
                                        USE_MOST_RECENT: false
                                        DRY_RUN: false
                                        TEST_LEVEL: 'NoTestRun'
                                        TESTS: ''
