parameters:
    - name: PACKAGE_VERSION_ID
      type: string
    - name: INSTALLATION_KEY
      type: string

stages:
    - stage: install_package_in_all_orgs
      displayName: 'Install package in all orgs'
      jobs:
          - job: 'Install_package'
            displayName: 'Install package'
            strategy:
                matrix:
                    INT:
                        TARGET_ORG: 'INT'
                    # QA:
                    #   TARGET_ORG: 'QA'
                    # UAT:
                    #   TARGET_ORG: 'UAT'
                    # PRODUCTION:
                    #   TARGET_ORG: 'PRODUCTION'
                    # TODO: add all environments
            container:
                image: nakamapartneringservices/nakama-pipelines
                endpoint: DockerHubNakama
            steps:
                - script: |
                      if [ "${{ parameters.INSTALLATION_KEY }}" != "false" ]; then
                          INSTALLATION_KEY_FLAG="--installation-key ${{ parameters.INSTALLATION_KEY }}"
                      fi
                      sf nakama install package -o $TARGET_ORG -p ${{ parameters.PACKAGE_VERSION_ID }} $INSTALLATION_KEY_FLAG
                  displayName: 'Install package $(TARGET_ORG)'
                  env:
                      INT_SFDX_AUTH_URL: $(INT_SFDX_AUTH_URL)
                      # QA_SFDX_AUTH_URL: $(QA_SFDX_AUTH_URL)
                      # UAT_SFDX_AUTH_URL: $(UAT_SFDX_AUTH_URL)
                      # PRODUCTION_SFDX_AUTH_URL: $(PRODUCTION_SFDX_AUTH_URL)
                      # TODO: add all environments
