parameters:
    - name: TARGET_ORG
      type: string
    - name: USE_MOST_RECENT
      type: boolean
    - name: DRY_RUN
      type: boolean
    - name: TEST_LEVEL
      type: string
    - name: TESTS
      type: string

stages:
    - stage: manual_deployment
      displayName: 'Manual deployment'
      jobs:
          - deployment: manual_deployment
            environment: ${{ parameters.TARGET_ORG }}
            displayName: 'Deploy to ${{ parameters.TARGET_ORG }}'
            container:
                image: nakamapartneringservices/nakama-pipelines
                endpoint: DockerHubNakama
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: deploy.yml
                              parameters:
                                  TARGET_ORG: ${{ parameters.TARGET_ORG }}
                                  USE_MOST_RECENT: ${{ parameters.USE_MOST_RECENT }}
                                  DRY_RUN: ${{ parameters.DRY_RUN }}
                                  TEST_LEVEL: ${{ parameters.TEST_LEVEL }}
                                  TESTS: ${{ parameters.TESTS }}
