stages:
    - stage: run_apex_tests
      displayName: 'Validation deployment with local tests'
      jobs:
          - job: 'Run apex tests'
            strategy:
                matrix:
                    INT:
                        TARGET_ORG: 'INT'
                    # QA:
                    #   ENVIRONMENT: 'QA'
                    # TODO: add lower environments
            container:
                image: nakamapartneringservices/nakama-pipelines
                endpoint: DockerHubNakama
            steps:
                - script: sf nakama validate tests -o $TARGET_ORG
                  displayName: 'Validate deployment executing local tests'
                  # Note: secret variables need to be declared here to be available.
                  env:
                      INT_SFDX_AUTH_URL: $(INT_SFDX_AUTH_URL)
                      # QA_SFDX_AUTH_URL: $(QA_SFDX_AUTH_URL)
                      # UAT_SFDX_AUTH_URL: $(QA_SFDX_AUTH_URL)
                      # TODO: add lower environments
