stages:
    - stage: run_apex_tests
      displayName: 'Validation deployment with local tests'
      jobs:
          - job: Run_apex_tests
            displayName: 'Run apex tests'
            strategy:
                matrix:
                    INT:
                        TARGET_ORG: 'INT'
                    # QA:
                    #   TARGET_ORG: 'QA'
                    # UAT:
                    #   TARGET_ORG: 'UAT'
                    # PRODUCTION:
                    #   TARGET_ORG: 'PRODUCTION'
                    # TODO: add main environments
            container:
                image: nakamapartneringservices/nakama-pipelines
                endpoint: DockerHubNakama
            steps:
                - script: sf nakama validate tests -o $TARGET_ORG
                  displayName: 'Validate deployment executing local tests'
                  # Note: secret variables need to be declared here to be available.
                  env:
                      INT_SFDX_AUTH_URL: $(INT_SFDX_AUTH_URL)
                      # QA_SFDX_AUTH_URL: $(QA_SFDX_AUTH_URL)
                      # UAT_SFDX_AUTH_URL: $(UAT_SFDX_AUTH_URL)
                      # PRODUCTION_SFDX_AUTH_URL: $(PRODUCTION_SFDX_AUTH_URL)
                      # TODO: add main environments

                - script: sf project deploy cancel --use-most-recent
                  condition: and(always(), eq(succeededOrFailed(), false))
                  displayName: 'Cancel deployment'
