parameters:
    - name: DESTINATION_ENVIRONMENT
      type: string

# Note: needs Pipelines > Manage Security > Edit build pipeline
steps:
    - script: |
          DESTINATION_ENVIRONMENT=${{ parameters.DESTINATION_ENVIRONMENT }}
          url="${SYSTEM_TEAMFOUNDATIONCOLLECTIONURI}${SYSTEM_TEAMPROJECTID}/_apis/build/definitions/${SYSTEM_DEFINITIONID}?api-version=5.0"
          build_pipeline=$(curl -X GET $url -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" -H "Content-Type: application/json")
          echo $build_pipeline > pipeline.json
          TARGET_VARIABLE="${DESTINATION_ENVIRONMENT}_LAST_DEPLOYMENT_COMMIT_SHA"
          jq --arg KEY "$TARGET_VARIABLE" --arg SOURCEVERSION "$BUILD_SOURCEVERSION" '.variables[$KEY]["value"] = $SOURCEVERSION' pipeline.json > updated_pipeline.json
          curl -X PUT $url -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" -H "Content-Type: application/json" -d @updated_pipeline.json
      displayName: 'Save Deployment Commit SHA'
      env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
