stages:
    - stage: validation_deployment_with_local_tests
      displayName: 'Validation deployment with local tests'
      jobs:
          - job: 'Validate'
            strategy:
                matrix:
                    DEVINT:
                        DESTINATION_ENVIRONMENT: 'DEVINT'
                    # TESTING:
                    #     DESTINATION_ENVIRONMENT: 'TESTING'
                    # STAGING:
                    #     DESTINATION_ENVIRONMENT: 'STAGING'
                    # PRODUCTION:
                    #     DESTINATION_ENVIRONMENT: 'PRODUCTION'
            container: salesforce/salesforcedx:latest-full
            steps:
                - script: |
                      sh ./scripts/shell/pipelines/validation-with-tests.sh $DESTINATION_ENVIRONMENT
                  displayName: 'Validation deployment'
                  # Secret variables need to be declared here to be mapped
                  env:
                      DEVINT_SFDX_AUTH_URL: $(DEVINT_SFDX_AUTH_URL)
                      # TESTING_SFDX_AUTH_URL: $(TESTING_SFDX_AUTH_URL)
                      # STAGING_SFDX_AUTH_URL: $(STAGING_SFDX_AUTH_URL)
                      # PRODUCTION_SFDX_AUTH_URL: $(PRODUCTION_SFDX_AUTH_URL)
