stages:
    - stage: validation_deployment_with_local_tests
      displayName: 'Validation deployment with local tests'
      jobs:
          - job: 'Validate'
            strategy:
                matrix:
                    CICD:
                        DESTINATION_ENVIRONMENT: 'CICD'
                    # QA:
                    #     DESTINATION_ENVIRONMENT: 'QA'
                    # UAT:
                    #     DESTINATION_ENVIRONMENT: 'UAT'
                    # PRODUCTION:
                    #     DESTINATION_ENVIRONMENT: 'PRODUCTION'
            container:
                image: nakamapartneringservices/nakama-pipelines
                endpoint: DockerHubNakama
            steps:
                - script: |
                      bash /validation-with-tests.sh $DESTINATION_ENVIRONMENT
                  displayName: 'Validation deployment'
                  # Secret variables need to be declared here to be mapped
                  env:
                      NAKAMA_ACCESS_TOKEN: $(NAKAMA_ACCESS_TOKEN)
                      CICD_SFDX_AUTH_URL: $(CICD_SFDX_AUTH_URL)
                      # QA_SFDX_AUTH_URL: $(QA_SFDX_AUTH_URL)
                      # UAT_SFDX_AUTH_URL: $(UAT_SFDX_AUTH_URL)
                      # PRODUCTION_SFDX_AUTH_URL: $(PRODUCTION_SFDX_AUTH_URL)
