stages:
    - stage: validation_deployment_with_local_tests
      displayName: 'Validation deployment with local tests'
      jobs:
          - job: 'Validate'
            strategy:
                matrix:
                    CICD:
                        DESTINATION_ENVIRONMENT: 'CICD'
                    # QA:
                    #     DESTINATION_ENVIRONMENT: 'QA'
                    # UAT:
                    #     DESTINATION_ENVIRONMENT: 'UAT'
                    # PRODUCTION:
                    #     DESTINATION_ENVIRONMENT: 'PRODUCTION'
            container: salesforce/salesforcedx:latest-full
            steps:
                - script: |
                      curl -s https://raw.githubusercontent.com/Nakama-Partnering-Services/nakama-project-scaffolding/main/scripts/shell/pipelines/validation-with-tests.sh > ./validation-with-tests.sh
                      chmod +x ./validation-with-tests.sh
                      ./validation-with-tests.sh $DESTINATION_ENVIRONMENT
                  displayName: 'Validation deployment'
                  # Secret variables need to be declared here to be mapped
                  env:
                      CICD_SFDX_AUTH_URL: $(CICD_SFDX_AUTH_URL)
                      # QA_SFDX_AUTH_URL: $(QA_SFDX_AUTH_URL)
                      # UAT_SFDX_AUTH_URL: $(UAT_SFDX_AUTH_URL)
                      # PRODUCTION_SFDX_AUTH_URL: $(PRODUCTION_SFDX_AUTH_URL)
