image: salesforce/salesforcedx:latest-full

stages:
    - scheduled-scratch-org-creation

create-scratch-orgs:
    stage: scheduled-scratch-org-creation
    rules:
        - if: $DAILY_SCRATCH_ORGS_CREATION_DISABLED
          when: never
    script:
        - sfdx auth:sfdxurl:store --sfdxurlfile $DEVHUB_SFDX_AUTH_URL --setdefaultdevhubusername
        - echo 'y' | sf plugins install sfpowerkit
        - sfdx sfpowerkit:pool:create --configfilepath=so_pool_config-base.schema.json
