deployments:
    environmentMapping:
        development:
            - 'ADMIN*'
            - 'DEV*'
        testing:
            - 'INT'
            - 'QA'
            - 'UAT'
        production:
            - 'PRODUCTION'
