image: salesforce/salesforcedx:latest-full

stages:
    - create-package-version
    - install-package-in-devhub

# TODO: apply something similar to github trailheadapps/github-action-sfdx-packaging-updater@1.1.0
# TODO: persist sfdx-project.json and README.md => Implement
create-package-version:
    stage: create-package-version
    script:
        - sfdx auth:sfdxurl:store --sfdxurlfile $DEVHUB_SFDX_AUTH_URL --setdefaultdevhubusername
        - json=$(sfdx force:package:version:create --package Frameworks --installationkeybypass --skipvalidation --wait 30 --json 3>&1) || true # --codecoverage
          # Note: Output is printed so that a possible error is not obscured
        - echo "Output ==> $json"
        - versionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
        - echo "versionId=$versionId" >> package.env
        - git config --local user.email "ci@gitlab.com"
        - git config --local user.name "GitLab CI Bot"
        - npx prettier --write sfdx-project.json
        - git add sfdx-project.json
        - git commit -m "Updated sfdx-project.json with new package version"
        - git remote show origin
        - git remote set-url --push origin git@gitlab:$CI_PROJECT_PATH
        - git remote show origin
        - git push origin HEAD:$CI_DEFAULT_BRANCH
    artifacts:
        reports:
            dotenv: package.env

install-package-in-devhub:
    stage: install-package-in-devhub
    allow_failure: true
    environment:
        name: scratch/$CI_COMMIT_REF_SLUG
        url: $SCRATCH_ORG_URL
    resource_group: scratch/$CI_COMMIT_REF_SLUG
    script:
        - sfdx auth:sfdxurl:store --sfdxurlfile $DEVHUB_SFDX_AUTH_URL --setdefaultdevhubusername
        - sfdx force:org:create --definitionfile config/project-scratch-def.json --setdefaultusername --durationdays 1
        # Note: replace scratch org creation if scratch org pool is needed
        # - echo 'y' | sf plugins install sfpowerkit
        # - sf sfpowerkit pool fetch --tag base --setdefaultusername
        - SCRATCH_ORG_DETAILS=$(sfdx force:org:open --urlonly --json)
        - SCRATCH_ORG_URL=$(jq -r '.result.url' <<< $SCRATCH_ORG_DETAILS)
        - echo "SCRATCH_ORG_URL=$SCRATCH_ORG_URL" >> scratch.env
        - sfdx force:package:install --package $versionId --publishwait 10 --wait 10 --noprompt
    artifacts:
        reports:
            dotenv: scratch.env
