image: salesforce/salesforcedx:latest-full

stages:
    - create-package-version
    - install-package-in-devhub

create-package-version:
    stage: create-package-version
    rules:
        - if: $CREATE_PACKAGE_VERSION_DISABLED
          when: never
    script:
        - sfdx auth:sfdxurl:store --sfdxurlfile $DEVHUB_SFDX_AUTH_URL --setdefaultdevhubusername
        - json=$(sfdx force:package:version:create --package Frameworks --installationkeybypass -c --wait 10 --json)
        - versionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
        # TODO: Persist sfdx-project.json and README.md
        - echo "versionId=$versionId" >> package.env
    artifacts:
        reports:
            dotenv: package.env

install-package-in-devhub:
    stage: install-package-in-devhub
    rules:
        - if: $CREATE_PACKAGE_VERSION_DISABLED
          when: never
    script:
        - sfdx auth:sfdxurl:store --sfdxurlfile $DEVHUB_SFDX_AUTH_URL --setdefaultusername
        - sfdx force:package:install --package $versionId --publishwait 10 --wait 10 --noprompt
