default:
    image: nakamapartneringservices/nakama-pipelines

.sfdx-changes:
    - force-app/**/*

stages:
    - deploy

deploy:
    stage: deploy
    rules:
        - if: $TARGET_ORG
          changes: !reference [.sfdx-changes]
    environment: $TARGET_ORG
    resource_group: $TARGET_ORG
    script:
        - source .env.replacements
        - sf nakama deploy deltas -o $TARGET_ORG -l NoTestRun
