default:
    image: nakamapartneringservices/nakama-pipelines

stages:
    - manual-deployment

manual-deployment:
    stage: manual-deployment
    environment: $TARGET_ORG
    resource_group: $TARGET_ORG
    script:
        - |
            if [ -n "$USE_MOST_RECENT" ]; then
                USE_MOST_RECENT_FLAG+="-r $USE_MOST_RECENT"
            fi
            if [ -n "$DRY_RUN" ]; then
                DRY_RUN_FLAG+="--dry-run $DRY_RUN"
            fi
            if [ -n "$TEST_LEVEL" ]; then
                TEST_LEVEL_FLAG+="-l $TEST_LEVEL"
            fi
            if [ -n "$TESTS" ]; then
                TESTS_FLAG+="-t $TESTS"
            fi
        - source .env.replacements
        - sf nakama deploy deltas -o $TARGET_ORG $USE_MOST_RECENT_FLAG $DRY_RUN_FLAG $TEST_LEVEL_FLAG $TESTS_FLAG
