default:
    image: salesforce/salesforcedx:latest-full

stages:
    - scheduled-tests
    - scheduled-tests-report

# Note: schedule this job rather than run-local-tests until this known issue is fixed https://trailblazer.salesforce.com/issues_view?id=a1p4V000002JRzNQAW
run-validation-deployment:
    stage: scheduled-tests
    rules:
        - if: $DAILY_VALIDATION_DEPLOYMENT_DISABLED
          when: never
        - if: $DESTINATION_ENVIRONMENT != ""
    environment: $DESTINATION_ENVIRONMENT
    resource_group: $DESTINATION_ENVIRONMENT
    script:
        - curl -s https://raw.githubusercontent.com/Nakama-Partnering-Services/nakama-project-scaffolding/main/scripts/shell/pipelines/validation-with-tests.sh > ./validation-with-tests.sh
        - chmod +x ./validation-with-tests.sh
        - ./validation-with-tests.sh $DESTINATION_ENVIRONMENT
    artifacts:
        when: always
        paths:
            - test-results/
        reports:
            junit: test-results/junit/junit.xml # Unit test reports only appear in the child dispatched pipeline
    # Also configurable in: project > Settings > CI/CD > Expand General pipelines, however that is deprecated
    # coverage: /name="testRunCoverage" value="([\d]+%)"/ not working since the --codecoverage flag can not be specified
    # and hence the testRunCoverage does not appear even if we print the junit.xml file in the job log.

run-local-tests:
    stage: scheduled-tests
    rules:
        - if: $DAILY_RUN_LOCAL_TESTS_DISABLED
          when: never
        - if: $DESTINATION_ENVIRONMENT != ""
    environment: $DESTINATION_ENVIRONMENT
    resource_group: $DESTINATION_ENVIRONMENT
    script:
        - DESTINATION_SFDX_AUTH_URL=$(eval echo \${${DESTINATION_ENVIRONMENT}_SFDX_AUTH_URL})
        - echo $DESTINATION_SFDX_AUTH_URL > ./DESTINATION_SFDX_AUTH_URL.txt
        - sfdx auth:sfdxurl:store --sfdxurlfile ./DESTINATION_SFDX_AUTH_URL.txt --setdefaultusername
        - TEST_RUN_DETAILS=$(sfdx force:apex:test:run --testlevel RunLocalTests --json)
        - TEST_RUN_ID=$(jq -r '.result.testRunId' <<< $TEST_RUN_DETAILS)
        - echo "TEST_RUN_ID ==> $TEST_RUN_ID"
        - echo "TEST_RUN_ID=$TEST_RUN_ID" >> test.env
    artifacts:
        reports:
            dotenv: test.env

run-local-tests-report:
    stage: scheduled-tests-report
    needs: [run-local-tests] # Since GitLab 14.2, needs does not need jobs to be on an earlier stage
    rules:
        - if: $DAILY_RUN_LOCAL_TESTS_DISABLED
          when: never
        - if: $DESTINATION_ENVIRONMENT != ""
          when: delayed
          start_in: 60 minutes
    environment: $DESTINATION_ENVIRONMENT
    resource_group: $DESTINATION_ENVIRONMENT
    script:
        - DESTINATION_SFDX_AUTH_URL=$(eval echo \${${DESTINATION_ENVIRONMENT}_SFDX_AUTH_URL})
        - echo $DESTINATION_SFDX_AUTH_URL > ./DESTINATION_SFDX_AUTH_URL.txt
        - sfdx auth:sfdxurl:store --sfdxurlfile ./DESTINATION_SFDX_AUTH_URL.txt --setdefaultusername
        - sfdx force:apex:test:report -i $TEST_RUN_ID --codecoverage --resultformat junit --outputdir ./tests/apex
    artifacts:
        reports:
            junit: tests/apex/*-junit.xml
    # Also configurable in: project > Settings > CI/CD > Expand General pipelines, however that is deprecated
    coverage: /name="testRunCoverage" value="([\d]+%)"/
