image: salesforce/salesforcedx:latest-full

stages:
    - scheduled-scratch-org-creation

create-scratch-orgs:
    stage: scheduled-scratch-org-creation
    rules:
        - when: always
    script:
        - sfdx auth:sfdxurl:store --sfdxurlfile $DEVHUB_SFDX_AUTH_URL --setdefaultdevhubusername
        - echo 'y' | sf plugins install sfpowerkit
        # Note: actions will still succeed if sfdx sfpowerkit:pool:create does not work as expected
        - sf sfpowerkit pool create --configfilepath=so_pool_config-base.schema.json
