image: salesforce/salesforcedx:latest-full

stages:
    - scheduled-tests
    - scheduled-tests-report

# Note: schedule this job rather than run-local-tests until this known issue is fixed https://trailblazer.salesforce.com/issues_view?id=a1p4V000002JRzNQAW
run-validation-deployment:
    stage: scheduled-tests
    rules:
        - if: $DAILY_VALIDATION_DEPLOYMENT_DISABLED
          when: never
        - if: $DESTINATION_ENVIRONMENT != ""
    environment: $DESTINATION_ENVIRONMENT
    resource_group: $DESTINATION_ENVIRONMENT
    script:
        - DESTINATION_SFDX_AUTH_URL=$(eval echo \${${DESTINATION_ENVIRONMENT^^}_SFDX_AUTH_URL})
        - sfdx auth:sfdxurl:store --sfdxurlfile $DESTINATION_SFDX_AUTH_URL --setdefaultusername
        - sfdx force:source:deploy --checkonly -m LightningComponentBundle:showToastUtility --testlevel RunLocalTests --verbose

run-local-tests:
    stage: scheduled-tests
    rules:
        - if: $DAILY_RUN_LOCAL_TESTS_DISABLED
          when: never
        - if: $DESTINATION_ENVIRONMENT != ""
    environment: $DESTINATION_ENVIRONMENT
    resource_group: $DESTINATION_ENVIRONMENT
    script:
        - DESTINATION_SFDX_AUTH_URL=$(eval echo \${${DESTINATION_ENVIRONMENT^^}_SFDX_AUTH_URL})
        - sfdx auth:sfdxurl:store --sfdxurlfile $DESTINATION_SFDX_AUTH_URL --setdefaultusername
        - TEST_RUN_DETAILS=$(sfdx force:apex:test:run --testlevel RunLocalTests --json)
        - TEST_RUN_ID=$(jq -r '.result.testRunId' <<< $TEST_RUN_DETAILS)
        - echo "TEST_RUN_ID ==> $TEST_RUN_ID"
        - echo "TEST_RUN_ID=$TEST_RUN_ID" >> test.env
    artifacts:
        reports:
            dotenv: test.env

run-local-tests-report:
    stage: scheduled-tests-report
    needs: [run-local-tests] # Since GitLab 14.2, needs does not needed jobs do not need to be on an earlier stage
    rules:
        - if: $DAILY_RUN_LOCAL_TESTS_DISABLED
          when: never
        - if: $DESTINATION_ENVIRONMENT != ""
          when: delayed
          start_in: 60 minutes
    environment: $DESTINATION_ENVIRONMENT
    resource_group: $DESTINATION_ENVIRONMENT
    script:
        - DESTINATION_SFDX_AUTH_URL=$(eval echo \${${DESTINATION_ENVIRONMENT^^}_SFDX_AUTH_URL})
        - sfdx auth:sfdxurl:store --sfdxurlfile $DESTINATION_SFDX_AUTH_URL --setdefaultusername
        - sfdx force:apex:test:report -i $TEST_RUN_ID --codecoverage --resultformat junit --outputdir ./tests/apex
    artifacts:
        reports:
            junit: tests/apex/*-junit.xml
    # Also configurable in: project > Settings > CI/CD > Expand General pipelines, however that is deprecated
    coverage: /name="testRunCoverage" value="([\d]+%)"/
