name: Dispatch deployment
on:
    push:
        branches:
            - main
            # Note: workflow dost not trigger when just pushing with --set-upstream to create the branch on remote.
            # It needs at least another commit to be pushed once branch is already created
            - rc/**
        paths:
            - sfdx-source/**

jobs:
    deploy-and-backpromote:
        strategy:
            matrix:
                DESTINATION_ENVIRONMENT: [DEVINT] # TESTING, TODO: add lower environments
        uses: ./.github/workflows/deploy-deltas.yml
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
            DESTINATION_ENVIRONMENT: ${{ matrix.DESTINATION_ENVIRONMENT }}
        secrets: inherit

    deploy-to-staging:
        uses: ./.github/workflows/deploy-deltas.yml
        if: ${{ startsWith( github.ref, 'refs/heads/rc/' ) }}
        with:
            DESTINATION_ENVIRONMENT: STAGING
        secrets: inherit
