name: Deploy to Testing and backpromote
on:
    push:
        branches:
            - main
            - rc/**
        paths:
            - sfdx-source/**

jobs:
    deploy-and-backpromote:
        strategy:
            matrix:
                DESTINATION: [DEVINT] # STAGING, PRODUCTION
        uses: ./.github/workflows/deploy-deltas.yml
        if: ${{ github.base_ref == 'refs/heads/main' }}
        with:
            DESTINATION: ${{ matrix.DESTINATION }}
        secrets: inherit

    deploy-to-staging:
        uses: ./.github/workflows/deploy-deltas.yml
        if: ${{ startsWith( github.base_ref, 'refs/heads/rc/' ) }}
        with:
            DESTINATION: STAGING
        secrets: inherit
