name: Deploy deltas

on:
    workflow_call:
        inputs:
            DESTINATION_ENVIRONMENT:
                required: true
                type: string

jobs:
    deploy-deltas:
        name: 'Deploy deltas'
        runs-on: ubuntu-latest
        container:
            image: nakamapartneringservices/nakama-pipelines
            credentials:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
        environment: ${{ inputs.DESTINATION_ENVIRONMENT }}
        concurrency:
            group: ${{ inputs.DESTINATION_ENVIRONMENT }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 'Load .env.replacements'
              uses: xom9ikk/dotenv@v2
              with:
                  path: ./
                  mode: replacements

            # Note: Tests do not run since it is redundant with PR and will take longer
            - name: 'Get deltas and deploy'
              env:
                  SFDX_AUTH_URL: ${{ inputs.DESTINATION_ENVIRONMENT }}_SFDX_AUTH_URL
                  LAST_DEPLOYMENT_COMMIT_SHA: ${{ inputs.DESTINATION_ENVIRONMENT }}_LAST_DEPLOYMENT_COMMIT_SHA
              run: |
                  export HOME=/root
                  git config --global --add safe.directory ${{ secrets.GIT_SAFE_DIRECTORY }}
                  echo ${{ secrets[env.SFDX_AUTH_URL] }} > ./DESTINATION_SFDX_AUTH_URL.txt
                  sfdx auth:sfdxurl:store --sfdxurlfile ./DESTINATION_SFDX_AUTH_URL.txt --setdefaultusername
                  bash /deploy.sh ${{ inputs.DESTINATION_ENVIRONMENT }} ${{ secrets[env.LAST_DEPLOYMENT_COMMIT_SHA] }} false NoTestRun

            - name: 'Update last deployment commit SHA'
              env:
                  LAST_DEPLOYMENT_COMMIT_SHA: ${{ inputs.DESTINATION_ENVIRONMENT }}_LAST_DEPLOYMENT_COMMIT_SHA
              uses: hmanzur/actions-set-secret@v2.0.0
              with:
                  name: ${{ env.LAST_DEPLOYMENT_COMMIT_SHA }}
                  value: ${{ github.sha }}
                  repository: ${{ github.repository }}
                  # Note: ${{ github.token }} does not work
                  token: ${{ secrets.PIPELINE_ACCESS_TOKEN }}
