name: Deploy
on:
    push:
        branches: main
        paths:
            - sfdx-source/**

jobs:
    deploy-git-deltas:
        name: 'Deploy git deltas'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: 'Restore node_modules cache'
              id: cache-npm
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-${{ env.cache-name }}-
                      npm-

            - name: 'Install npm dependencies'
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: npm ci

            - name: Install Salesforce CLI
              run: npm install sfdx-cli --global

            - name: 'Create Dev Hub auth file'
              run: echo ${{ secrets.DEVHUB_SFDX_AUTH_URL }} > ./DEVHUB_SFDX_AUTH_URL.txt

            - name: 'Authorize Dev Hub'
              run: sfdx auth:sfdxurl:store --sfdxurlfile ./DEVHUB_SFDX_AUTH_URL.txt --setalias 'Nakama Dev Hub' --setdefaultdevhubusername --setdefaultusername

            - name: 'Remove Dev Hub auth file'
              run: rm --force ./DEVHUB_SFDX_AUTH_URL.txt

            - name: 'Install SFDX Git Delta'
              run: sf plugins install sfdx-git-delta

            - name: 'Generate manifest files with git deltas'
              run: |
                  sf sgd source delta --source sfdx-source --from HEAD^ --to HEAD --output . --ignore .forceignore

            # Note: it is not done by installing unlocked packages, since this way we can also leverage destructive changes and deploy metadata which can not be packaged
            - name: 'Deploy executing local test'
              run: sfdx force:source:deploy --manifest package/package.xml --postdestructivechanges destructiveChanges/destructiveChanges.xml --testlevel RunLocalTests --verbose
