name: 'Lint pull request'

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize
        branches-ignore:
            - rc/**-comparison

permissions:
    pull-requests: read

jobs:
    main:
        name: 'Validate pull request title'
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: 'Verify title contains Jira key'
              run: |
                  ticket_number=$(echo "${{ github.head_ref }}" | sed -n -E 's/^(feature|bugfix|hotfix|chore|comparison)\/([A-Z]+-[0-9]+).*/\2/p')
                  if [ -z "$ticket_number" ]; then
                    echo "The branch does not contain the Jira Key, check https://checkatrade.atlassian.net/wiki/spaces/SD/pages/3448569863/DevOps+Documentation+-+DevOps+Strategies+Vertex"
                    exit 1
                  fi
                  if [[ ! "${{ github.event.pull_request.title }}" == *"$ticket_number"* ]]; then
                    echo "The Pull Request title does not contain the Jira Key, fix it accordingly."
                    exit 1
                  fi
