name: Manual deployment
on:
    workflow_dispatch:
        inputs:
            destination:
                description: 'Destination environment for the manual deployment. Mainly used for deployments to UAT and PRODUCTION.'
                required: true
                type: choice
                options:
                    - CICD
                    # - QA
                    # - UAT
                    # - PRODUCTION
                    # - HOTFIX
            checkonly:
                description: 'If true, changes are not actually deployed, but just validated.'
                required: false
                type: boolean
            testlevel:
                description: 'Specifies which level of deployment tests to run. Valid values are:'
                default: RunLocalTests
                required: false
                type: choice
                options:
                    - NoTestRun
                    - RunSpecifiedTests
                    - RunLocalTests
                    - RunAllTestsInOrg
            runtests:
                description: 'Lists of the Apex classes containing the deployment tests to run. Use this parameter when you set testlevel to RunSpecifiedTests. Default value is based on autoidentified test classes.'
                type: string
                required: false

jobs:
    deploy-deltas:
        name: 'Deploy deltas'
        runs-on: ubuntu-latest
        container:
            image: nakamapartneringservices/nakama-pipelines
            credentials:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
        environment: ${{ github.event.inputs.destination }}
        concurrency:
            group: ${{ github.event.inputs.destination }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 'Load .env.replacements'
              uses: xom9ikk/dotenv@v2
              with:
                  path: ./
                  mode: replacements

            - name: 'Get deltas and deploy'
              env:
                  SFDX_AUTH_URL: ${{ github.event.inputs.destination }}_SFDX_AUTH_URL
                  LAST_DEPLOYMENT_COMMIT_SHA: ${{ github.event.inputs.destination }}_LAST_DEPLOYMENT_COMMIT_SHA
              run: |
                  export HOME=/root
                  git config --global --add safe.directory $GITHUB_WORKSPACE
                  echo ${{ secrets[env.SFDX_AUTH_URL] }} > ./DESTINATION_SFDX_AUTH_URL.txt
                  sfdx auth:sfdxurl:store --sfdxurlfile ./DESTINATION_SFDX_AUTH_URL.txt --setdefaultusername
                  bash /deploy.sh ${{ github.event.inputs.destination }} ${{ secrets[env.LAST_DEPLOYMENT_COMMIT_SHA] }} ${{ github.event.inputs.checkonly }} ${{ github.event.inputs.testlevel }} ${{ github.event.inputs.runtests }}

            - name: 'Update last deployment commit SHA'
              # https://github.com/actions/runner/issues/1483
              if: github.event.inputs.checkonly == 'false'
              env:
                  LAST_DEPLOYMENT_COMMIT_SHA: ${{ github.event.inputs.destination }}_LAST_DEPLOYMENT_COMMIT_SHA
              uses: hmanzur/actions-set-secret@v2.0.0
              with:
                  name: ${{ env.LAST_DEPLOYMENT_COMMIT_SHA }}
                  value: ${{ github.sha }}
                  repository: ${{ github.repository }}
                  token: ${{ secrets.PIPELINE_ACCESS_TOKEN }}
