name: Daily run local tests
on:
    schedule:
        - cron: '0 23 * * *'
    workflow_dispatch:

jobs:
    run-local-tests:
        name: 'Run Local Tests'
        runs-on: ubuntu-latest
        container:
            # Warning: when running in container, git commands will not work since it will not be a repository
            image: docker://salesforce/salesforcedx:latest-full
        strategy:
            fail-fast: false
            matrix:
                DESTINATION_ENVIRONMENT: [CICD] # , QA, UAT, PRODUCTION, HOTFIX
        environment: ${{ matrix.DESTINATION_ENVIRONMENT }}
        concurrency: ${{ matrix.DESTINATION_ENVIRONMENT }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v2

            - name: 'Create Destination auth file'
              env:
                  SFDX_AUTH_URL: ${{ matrix.DESTINATION_ENVIRONMENT }}_SFDX_AUTH_URL
              run: echo ${{ secrets[env.SFDX_AUTH_URL] }} > ./DESTINATION_SFDX_AUTH_URL.txt

            - name: 'Authorize Destination'
              run: sfdx auth:sfdxurl:store --sfdxurlfile ./DESTINATION_SFDX_AUTH_URL.txt --setdefaultusername

            - name: 'Remove Destination auth file'
              run: rm --force ./DESTINATION_SFDX_AUTH_URL.txt

            # Note: sfdx force:apex:test:run not used until this known issue is fixed https://trailblazer.salesforce.com/issues_view?id=a1p4V000002JRzNQAW
            - name: 'Validation deployment executing local tests'
              run: |
                  curl -s https://raw.githubusercontent.com/Nakama-Partnering-Services/nakama-project-scaffolding/main/scripts/shell/pipelines/validation-with-tests.sh > ./validation-with-tests.sh
                  chmod +x ./validation-with-tests.sh
                  ./validation-with-tests.sh
