name: Daily run local tests
on:
    schedule:
        - cron: '0 23 * * *'
    workflow_dispatch:

jobs:
    run-local-tests:
        name: 'Run Local Tests'
        runs-on: ubuntu-latest
        container:
            image: nakamapartneringservices/nakama-pipelines
            credentials:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
        strategy:
            fail-fast: false
            matrix:
                DESTINATION_ENVIRONMENT: [CICD] # , QA, UAT, PRODUCTION, HOTFIX
        environment: ${{ matrix.DESTINATION_ENVIRONMENT }}
        concurrency: ${{ matrix.DESTINATION_ENVIRONMENT }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3

            - name: 'Validation deployment executing local tests'
              env:
                  SFDX_AUTH_URL: ${{ matrix.DESTINATION_ENVIRONMENT }}_SFDX_AUTH_URL
              run: |
                  echo ${{ secrets[env.SFDX_AUTH_URL] }} > ./DESTINATION_SFDX_AUTH_URL.txt
                  sfdx auth:sfdxurl:store --sfdxurlfile ./DESTINATION_SFDX_AUTH_URL.txt --setdefaultusername
                  bash /validation-with-tests.sh
