name: Create Scratch orgs in pool for PR validations
on:
    schedule:
        - cron: '0 23 * * *'
    workflow_dispatch:

jobs:
    create-scratch-orgs:
        name: 'Create Scratch orgs'
        runs-on: ubuntu-latest
        container:
            # Warning: when running in container, git commands will not work since it will not be a repository
            image: docker://salesforce/salesforcedx:latest-full
        steps:
            - uses: actions/checkout@v2

            - name: 'Create Dev Hub auth file'
              run: echo ${{ secrets.DEVHUB_SFDX_AUTH_URL }} > ./DEVHUB_SFDX_AUTH_URL.txt

            - name: 'Authorize Dev Hub'
              run: sfdx auth:sfdxurl:store --sfdxurlfile ./DEVHUB_SFDX_AUTH_URL.txt --setdefaultdevhubusername

            - name: 'Remove Dev Hub auth file'
              run: rm --force ./DEVHUB_SFDX_AUTH_URL.txt

            - name: 'Create base Scratch orgs in pool'
              run: |
                  set -e
                  echo 'y' | sfdx plugins:install sfpowerkit
                  sfdx sfpowerkit:pool:create --configfilepath=so_pool_config-base.schema.json
